### ISSUE TITLE
APIs for java

### ISSUE THREAD

**Issue by charantejapandalaneni** [aws-samples/amazon-chime-sdk#25]
Do we have java apis for building a chat feature using amazon chime SDK ?
amazon chime java sdk git repo or a demo application (not for android)?

**Comment by ltrung** [comment]
We currently do not have a demo for a chat application using Java. However, all the chat APIs are available in AWS SDK for Java. 
The only thing you would need outside of AWS SDK is to create a websocket connection to [getMessagingSessionEndpoint](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/chime/AmazonChime.html#getMessagingSessionEndpoint-com.amazonaws.services.chime.model.GetMessagingSessionEndpointRequest-) in order to receive messages in real time.

**Comment by charantejapandalaneni** [comment]
how to create a channel for cognito pool users and start messaging instance using java or how to enable chat feature between two cognito pool users using backend java

**Comment by dpwspoon** [comment]
The chat messaging APIs can be called from clients or servers, but are client centric.  APIs are called as a specific user and that has meaning, like who sent a message or created a channel.  This means they take a parameter "chime-bearer" that represents the client they are being called from.  The chime-bearer is an app instance user arn.  See https://github.com/aws-samples/amazon-chime-sdk/issues/18 for example API calls using it.

A client side application will have IAM permissions scoped to specific users ([IAM policy example](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat/src/backend/serverless/template.yaml#L557)). 

If calling APIs from a server you have 2 options: (1) make a new user like "backend" and make API calls from the backend as that user, or (2) give permissions to the backend on app instance user arn "/*", and have the backend make API calls on behalf of the users.  The first case is generally used if you want the backend to control channels or send out generic messages.  The latter is used if you want backend logic to drive client interactions, such as sending status updates for clients when a client may or may not be online.
